todos_indicadores = ['77818 - Economia: Chegada de turistas',
                     '77819 - Economia: Gastos públicos com educação',
                     '77820 - Economia: Gastos públicos com saúde',
                     '77821 - Economia: Investimentos em pesquisa e desenvolvimento',
                     '77822 - Economia: Mulheres de 15 anos ou mais de idade economicamente ativas',
                     '77823 - Economia: PIB per capita',
                     '77824 - Economia: População de 15 anos ou mais de idade economicamente ativa',
                     '77825 - Economia: Total de exportações',
                     '77826 - Economia: Total de importações',
                     '77827 - Economia: Total do PIB',
                     '77830 - Indicadores sociais: Esperança de vida ao nascer',
                     '77831 - Indicadores sociais: Índice de desenvolvimento humano',
                     '77832 - Indicadores sociais: População com acesso à água potável',
                     '77833 - Indicadores sociais: População com acesso à rede sanitária',
                     '77835 - Indicadores sociais: Taxa bruta de matrículas para todos os níveis de ensino',
                     '77836 - Indicadores sociais: Taxa de alfabetização das pessoas de 15 anos ou mais de idade',
                     '77838 - Meio Ambiente: Áreas cultivadas',
                     '77839 - Meio Ambiente: Áreas de pastagens permanentes',
                     '77840 - Meio Ambiente: Áreas protegidas no total do território nacional',
                     '77841 - Meio Ambiente: Produção de gás natural',
                     '77842 - Meio Ambiente: Produção de petróleo',
                     '77844 - População: Densidade demográfica',
                     '77845 - População: Homens',
                     '77846 - População: Mulheres',
                     '77847 - População: População residente em área rural',
                     '77848 - População: População residente em área urbana',
                     '77849 - População: População',
                     '77850 - População: Taxa bruta de mortalidade',
                     '77851 - População: Taxa bruta de natalidade',
                     '77852 - População: Taxa média anual do crescimento da população',
                     '77854 - Redes: Assinaturas de telefonia celular',
                     '77855 - Redes: Assinaturas de telefonia fixa',
                     '77857 - Redes: Indivíduos com acesso à internet',
                     '77829 - Saúde  - Consumo calórico',
                     '77834 - Saúde  - Incidência de subnutrição']

todos_paises = ['AF - Afeganistão',
                'ZA - África do Sul',
                'AL - Albânia',
                'DE - Alemanha',
                'AD - Andorra',
                'AO - Angola',
                'AG - Antígua e Barbuda',
                'SA - Arábia Saudita',
                'DZ - Argélia',
                'AR - Argentina',
                'AM - Armênia',
                'AU - Austrália',
                'AT - Áustria',
                'AZ - Azerbaijão',
                'BS - Bahamas',
                'BD - Bangladesh',
                'BB - Barbados',
                'BH - Barein',
                'BY - Belarus',
                'BE - Bélgica',
                'BZ - Belize',
                'BJ - Benin',
                'BO - Bolívia',
                'BA - Bósnia e Herzegovina',
                'BW - Botsuana',
                'BR - Brasil',
                'BN - Brunei',
                'BG - Bulgária',
                'BF - Burkina Faso',
                'BI - Burundi',
                'BT - Butão',
                'CV - Cabo Verde',
                'CM - Camarões',
                'KH - Camboja',
                'CA - Canadá',
                'QA - Catar',
                'KZ - Cazaquistão',
                'TD - Chade',
                'CL - Chile',
                'CN - China',
                'CY - Chipre',
                'CO - Colômbia',
                'KM - Comores',
                'CG - Congo',
                'CI - Costa do Marfim',
                'CR - Costa Rica',
                'HR - Croácia',
                'CU - Cuba',
                'DK - Dinamarca',
                'DJ - Djibouti',
                'DM - Dominica',
                'EG - Egito',
                'SV - El Salvador',
                'AE - Emirados Árabes Unidos',
                'EC - Equador',
                'ER - Eritréia',
                'SK - Eslováquia',
                'SI - Eslovênia',
                'ES - Espanha',
                'US - Estados Unidos da América',
                'EE - Estônia',
                'SZ - Eswatini',
                'ET - Etiópia',
                'FJ - Fiji',
                'PH - Filipinas',
                'FI - Finlândia',
                'FR - França',
                'GA - Gabão',
                'GM - Gâmbia',
                'GH - Gana',
                'GE - Geórgia',
                'GD - Granada',
                'GR - Grécia',
                'GT - Guatemala',
                'GY - Guiana',
                'GN - Guiné',
                'GQ - Guiné Equatorial',
                'GW - Guiné-Bissau',
                'HT - Haiti',
                'NL - Holanda',
                'HN - Honduras',
                'HU - Hungria',
                'YE - Iêmen',
                'MH - Ilhas Marshall',
                'SB - Ilhas Salomão',
                'IN - Índia',
                'ID - Indonésia',
                'IR - Irã',
                'IQ - Iraque',
                'IE - Irlanda',
                'IS - Islândia',
                'IL - Israel',
                'IT - Itália',
                'JM - Jamaica',
                'JP - Japão',
                'JO - Jordânia',
                'KI - Kiribati',
                'KW - Kuwait',
                'LA - Laos',
                'LS - Lesoto',
                'LV - Letônia',
                'LB - Líbano',
                'LR - Libéria',
                'LY - Líbia',
                'LI - Liechtenstein',
                'LT - Lituânia',
                'LU - Luxemburgo',
                'MK - Macedônia do Norte',
                'MG - Madagáscar',
                'MY - Malásia',
                'MW - Malauí',
                'MV - Maldivas',
                'ML - Mali',
                'MT - Malta',
                'MA - Marrocos',
                'MU - Maurício',
                'MR - Mauritânia',
                'MX - México',
                'MM - Mianmar',
                'FM - Micronésia',
                'MZ - Moçambique',
                'MD - Moldávia',
                'MC - Mônaco',
                'MN - Mongólia',
                'ME - Montenegro',
                'NA - Namíbia',
                'NR - Nauru',
                'NP - Nepal',
                'NI - Nicarágua',
                'NE - Níger',
                'NG - Nigéria',
                'NO - Noruega',
                'NZ - Nova Zelândia',
                'OM - Omã',
                'PW - Palau',
                'PA - Panamá',
                'PG - Papua Nova Guiné',
                'PK - Paquistão',
                'PY - Paraguai',
                'PE - Peru',
                'PL - Polônia',
                'PT - Portugal',
                'KE - Quênia',
                'KG - Quirguistão',
                'GB - Reino Unido',
                'CF - República Centro Africana',
                'KR - República da Coréia',
                'CD - República Democrática do Congo',
                'DO - República Dominicana',
                'KP - República Popular Democrática da Coréia',
                'CZ - República Tcheca',
                'RO - Romênia',
                'RW - Ruanda',
                'RU - Rússia (Federação Russa)',
                'WS - Samoa',
                'SM - San Marino',
                'LC - Santa Lúcia',
                'KN - São Cristóvão e Nevis',
                'ST - São Tomé e Príncipe',
                'VC - São Vicente e Granadinas',
                'SC - Seichelles',
                'SN - Senegal',
                'SL - Serra Leoa',
                'RS - Sérvia',
                'SG - Singapura',
                'SY - Síria',
                'SO - Somália',
                'LK - Sri Lanka',
                'SD - Sudão',
                'SS - Sudão do Sul',
                'SE - Suécia',
                'CH - Suíça',
                'SR - Suriname',
                'TJ - Tadjiquistão',
                'TH - Tailândia',
                'TZ - Tanzânia',
                'TL - Timor Leste',
                'TG - Togo',
                'TO - Tonga',
                'TT - Trinidad e Tobago',
                'TN - Tunísia',
                'TM - Turcomenistão',
                'TR - Turquia',
                'TV - Tuvalu',
                'UA - Ucrânia',
                'UG - Uganda',
                'UY - Uruguai',
                'UZ - Uzbequistão',
                'VU - Vanuatu',
                'VE - Venezuela',
                'VN - Vietnã',
                'ZM - Zâmbia',
                'ZW - Zimbábue']
