POSTGRES_USERNAME="onu_ibge_project_user"
POSTGRES_PASSWORD="1a8F1RRnMU0Xb00IcoydHynIrJ2WE96P"
POSTGRES_HOST="dpg-crcekh5svqrc73cj2na0-a.oregon-postgres.render.com"
POSTGRES_PORT="5432"
POSTGRES_DB="onu_ibge_project"

